export const ADD_STUDENT_REQUEST = 'students/ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCCESS = 'students/ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILURE = 'students/ADD_STUDENT_FAILURE';

export const FETCH_STUDENTS_REQUEST = 'students/FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'students/FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'students/FETCH_STUDENTS_FAILURE';

export const FETCH_STUDENT_REQUEST = 'students/FETCH_STUDENT_REQUEST';
export const FETCH_STUDENT_SUCCESS = 'students/FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAILURE = 'students/FETCH_STUDENT_FAILURE';
